### ISSUE TITLE
MSI: We noticed that out-of-stock products were still exported to Tweakwise.

### ISSUE THREAD

**Issue by RemcoWolterink** [EmicoEcommerce/Magento2TweakwiseExport#27]
Issue Brief
--
We noticed that out-of-stock products were still exported to Tweakwise.

Environment
--
- [ ] Magento Version: 2.4.5-p5
- [ ] Magento Enterprise: (yes)
- [ ] Tweakwise Export Version: 5.3.0

Steps to reproduce
--
1. Install Magento from `master` branch.
2. Set-up MSI with two sources (webshop & store).
4. Create a situation for a product where the source called Webshop has qty 0 and stock status "in stock":
5. Export the feed to tweakwise.

Actual result
--
Export the product to tweakwise and you see that the product is still exported as it shouldn't.

In the index table( inventory_stock_* ) that Magento uses to determine if the product is in stock or out of stock, the product is, as expected, out of stock.

Tweakwise instead of checking the Magentio indexed table, checks the MAX stock status value of the sources.

Expected result
--
List the expected results as a bullet list of expectations
- [ ] Index table is used for the stock status if MSI is active.

**Comment by ahuininga-orisha** [comment]
@RemcoWolterink I'll discuss this internally. The problem is that we may not have the same definition of out of stock. If you have an product status of "in stock" the product is in stock regardless of the quantity. 

We will discuss this internally and see IF we are going to change this.

**Comment by RemcoWolterink** [comment]
Adobe commerce MSI have a different definition than the default stock logic.

**Comment by ahuininga-orisha** [comment]
@RemcoWolterink I'm missing some information to reproduce this issue.

You have two stock sources. But you don't explain if they are configured for the same website, of if you use different website/store views under stores->inventory->stocks. Also the value for the other stock source isn't given.

Can you give the exact configuration for stores->inventory->stocks, and stores->inventory->sources. And the stock for the product for all sources for that product?

If both stock sources are configured for the same website. And the first has an quantity of 0, but the second has an stock of 10. Then the products gets exported because there are 10 in stock in an different stock location. And that stock location is available for that website.

**Comment by RemcoWolterink** [comment]
@ah-net I hope this will help you to reproduce this issue:

1 website with multiple store views.

MSI set-up:

Sources:
Webshop stock | Enabled 
Store stock | Disabled

Stock:
One stock on website level for combined values.

Product with:
Webshop stock (enabled): 0 
Stock status: In stock.

Store stock (disabled): 20
Stock status: In stock.

So in this case the product has a salable quantity of 0, but it depends on the stock status. But that is by default not changed by Magento if a product goes out of stock. But your logic relies on this stock status and as far as i know that is wrong. It should take into account the value in the index.

**Comment by ahuininga-orisha** [comment]
@RemcoWolterink I think you have encountered this bug that was recently fixed.

https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/23

That bug exports stock of disabled stock sources. So in the case of the example. The product is exported because the export thinks the product has 20 stock. 

This was recently fixed, so the export only checks the enabled stock source (in the example 0) en should now not export the product anymore.

I would expect that you don't have this problem anymore in the latest version.

**Comment by RemcoWolterink** [comment]
We still have the issue there. We already applied that fix.

The issue is about the stock Status vs Stock Qty. So if the stock situation is like described. The product is still exported, as there is 0 stock qty available.

**Comment by ahuininga-orisha** [comment]
@RemcoWolterink I'll take another look at this and see if i can reproduce the issue

**Comment by ahuininga-orisha** [comment]
@RemcoWolterink I still can't reproduce the issue.

When I use your example in magento commerce the "is_in_stock" column of the cataloginventory_stock_item table is set to 0. This is the column the export checks. And the product isn't exported. Is this column set to 0 or 1 in your case? If it's set to 1 then that is the problem. It should be set to 0 by magento.

**Comment by sergiozt** [comment]
Hello @ah-net 
The "cataloginventory_stock_item" is the legacy table that is not the main one when the MSI is enabled.
[In the code ](https://github.com/EmicoEcommerce/Magento2TweakwiseExport/blob/97f1fd953c65db01f4d153532f3810e699ec1db8/Model/Write/Products/CollectionDecorator/StockData/SourceItemMapProvider.php#L145) here you check the table, but not the final one(indexed table) that contains statuses, the table name is "inventory_stock_*" where * - stock id.
Example: where/how Magento does that with MSI:
![image](https://github.com/EmicoEcommerce/Magento2TweakwiseExport/assets/5140641/4f65d7e2-5353-4c7d-b71c-cacb9169e755)



![image](https://github.com/EmicoEcommerce/Magento2TweakwiseExport/assets/5140641/87858773-3161-40aa-b86a-6aebd4460a43)

**Comment by ahuininga-orisha** [comment]
@sergiozt Thx for the explanation. Ill look into this again. I think i finally understand the issue here.

**Comment by sergiozt** [comment]
Hello @ah-net 
We see that there is a fix for that issue you did and. merged into the branch: https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/65/commits 
Amazing news! When are you planning to include it into the specific version/tag?

**Comment by ahuininga-orisha** [comment]
@sergiozt Next week there wil be an new release.

**Comment by ahuininga-orisha** [comment]
Released in version 7.1.0

**Comment by sergiozt** [comment]
Amazing news @ah-net , thanks for the fix.
